version: 2
jobs:
  build_wallet:
    macos:
      xcode: "12.2.0"

    steps:
      # Checkout repo
      - checkout

      # Save/Restore cache
      #- save_cache:
      #    key: wallet_cache
      #    paths:
      #      - node_modules
      #      - ~/.npm
      #      - ~/.meteor

      #- restore_cache:
      #    key: wallet_cache
      
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            npm install -g n
            sudo n 8.11.4
            brew update
            brew cleanup
            # brew cask install google-chrome
            # brew cask install chromedriver

      # Prepare app
      - run:
          name: Install meteor v1.8.0.2
          command: |
            if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
            if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com/?release=1.8.0.2 | sh; fi
      # - run:
      #     name: update npm to latest
      #     command: |
      #       npm i npm@latest -g
      - run:
          name: install snyk globally
          command: |
            npm i snyk -g && sudo chown -R $USER:$(id -gn $USER) /Users/distiller/.config
      - run:
          name: install dependencies
          command: |
            rm package-lock.json && rm .electrify/package-lock.json && npm install
      - run:
          name: install electrify-qrl globally
          command: |
            npm install -g electrify-qrl
      - run:
          name: report meteor node version
          command: |
            meteor node -e 'console.log("I am Node.js %s!", process.version);'

      # Start meteor in background
      #- run:
      #    name: Start Meteor
      #    command: |
      #      meteor npm install --unsafe-perm
      #      npm run dev
      #    background: true

      # Run unit tests
      #- run:
      #    name: Run selenium tests
      #    command: |
      #      until curl --max-time 300 http://localhost:3000/; do sleep 1; done
      #      #npm install -g chimp
      #      #npm install -g selenium-standalone
      #      #/usr/local/Cellar/node/8.7.0/bin/chimp --ddp=http://localhost:3000 --browser=chrome --path=tests

      # Create package on master
      - deploy:
          command:  |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm install -g electrify-qrl
              npm install
              export NODEPATH=/usr/local/Cellar/node/8.7.0
              export PATH="$NODEPATH/bin:$PATH"
              # Package Electron App
              npm run cleanDist
              npm run releaseready
              npm run build
              # Build Macos DMG
              npm run installer
              # Clear Electron build folder
              rm -rf ./.electrify/.dist/QRLWallet-darwin-x64
            fi
            if [ "${CIRCLE_BRANCH}" == "devnet" ]; then
              npm install -g electrify-qrl
              npm install
              export NODEPATH=/usr/local/Cellar/node/8.7.0
              export PATH="$NODEPATH/bin:$PATH"
              # Package Electron App
              npm run cleanDist
              npm run releaseready
              npm run build
              # Build Macos DMG
              npm run installer
              # Clear Electron build folder
              rm -rf ./.electrify/.dist/QRLWallet-darwin-x64
            fi
      # Save artifacts
      - store_artifacts:
          path: .electrify/.dist/
          destination: build

workflows:
  version: 2
  build_all:
    jobs:
      - build_wallet
